services:
  signal:
    image: netbirdio/signal:${APP_TAG}
    container_name: netbird-signal
    restart: unless-stopped
    volumes:
      - ${INSTALL_DIR}/data/config/signal:/var/lib/netbird

  management:
    image: netbirdio/management:${APP_TAG}
    container_name: netbird-management
    restart: unless-stopped
    depends_on:
      - signal
    volumes:
      - ${INSTALL_DIR}/data/config/management:/var/lib/netbird
      - ${INSTALL_DIR}/data/config/management.json:/etc/netbird/management.json:ro
    command: [
      "--port", "80",
      "--log-file", "console",
      "--disable-anonymous-metrics",
      "--single-account-mode-domain", "${NETBIRD_DOMAIN}",
      "--dns-domain", "netbird.selfhosted"
    ]

  dashboard:
    image: netbirdio/dashboard:v2.4.1
    container_name: netbird-dashboard
    restart: unless-stopped
    ports:
      - "${EXPOSE_PORT:-443}:443"
      - "80:80"
    environment:
      - AUTH_SUPPORTED_SCOPES=openid profile email offline_access api
      - AUTH_AUDIENCE=${OIDC_CLIENT_ID:-netbird}
      - AUTH_AUTHORITY=${AUTHENTIK_URL:-}/application/o/netbird/
      - NETBIRD_MGMT_API_ENDPOINT=https://${NETBIRD_DOMAIN}:443
      - NETBIRD_MGMT_GRPC_API_ENDPOINT=https://${NETBIRD_DOMAIN}:443

  coturn:
    image: coturn/coturn:4.6.2
    container_name: netbird-coturn
    restart: unless-stopped
    network_mode: host
    volumes:
      - ${INSTALL_DIR}/data/config/turnserver.conf:/etc/coturn/turnserver.conf:ro
